### ISSUE TITLE
S3 Bucket Name Change

### ISSUE THREAD

**Issue by joelferrier** [ThreatResponse/aws_ir#27]
@andrewkrug, @amccormack  Do you guys see value in including the `case-number` into generated s3 bucket names?

Perhaps something like this:
`cloud-response-0b41c684836f47518a7d05db3adc756e` ->
`cloud-response-cr-17-022605-3da6-0b41c684836f47518a7d05db3adc756e`

This would also make it easier for aws_ir to reuse a case bucket for without forcing both the `case-number` and `bucket-name` to be specified.

**Comment by andrewkrug** [comment]
There's a maximum limit characters in names.  This could work with a compressed form of the uuid though.  Like a hashid style name.
