### ISSUE TITLE
log metadata in valid json

### ISSUE THREAD

**Issue by amccormack** [ThreatResponse/aws_ir#4]
currently logged as python blob.

**Comment by andrewkrug** [comment]
Just to clarify this is related to the log file of actions taken by ThreatResponse during it's initial run.

**Comment by amccormack** [comment]
@andrewkrug I've noticed this in the cr-*-console.log file and the cr-*-aws_ir.log files

**Comment by andrewkrug** [comment]
@amccormack one of those files is created by our logger class cr--aws_ir .  The other is pulled straight out of the API and likely needs a little massaging.
