### ISSUE TITLE
GPG key trust issue

### ISSUE THREAD

**Issue by andrewkrug** [ThreatResponse/aws_ir#46]
When attempting a run during mem acquisition the following error is thrown by marsho
```
2017-05-13T14:49:19 - aws_ir.plans.host - INFO - Attempting run margarita shotgun for ubuntu on 35.167.170.172 with /Users/krug/Downloads/testing.pem
2017-05-13T14:49:19 - margaritashotgun.client - CRITICAL - Repository signing key found at https://threatresponse-lime-modules.s3.amazonaws.com/REPO_SIGNING_KEY.asc is not trusted on the local system, fingerprint: 80DA92CB09161F241C8F9BC918BA980367172B17
```

Document or provide logic to install the key.  

My OS is MacOS Sierra
Acquisition OS is 14.04 Ubuntu HVM

**Comment by andrewkrug** [comment]
Any thoughts on this one @joelferrier

**Comment by joelferrier** [comment]
@andrewkrug I think we should do both.

1. Prompt the user to install the key, and continue/retry memory capture after the key has been installed.  I'm not sure if it's best for this to be implemented in aws_ir, or in margarita shotgun
2. Document installing the threat response signing key once it's published to a key server and the email address security@threatresponse.cloud has been created.  This documentation should be included in both the aws_ir and margarita shotgun repositories 

Right now I'm leaning towards implementing option 1 in margarita shotgun, we may want to add a flag that disables interactive elements in conjunction with this.

**Comment by andrewkrug** [comment]
@joelferrier I think non-interactive should be the default and prompts enabled with a --interactive flag.  Since most people are running in a non-intervention kind of mode.  

> Prompt the user to install the key, and continue/retry memory capture after the key has been installed. I'm not sure if it's best for this to be implemented in aws_ir, or in margarita shotgun

^^ Agree on this.

**Comment by joelferrier** [comment]
@andrewkrug after some thought I think the GPG key handling should be implemented in margarita shotgun.

I don't agree with you about non-interactive being the default when it comes to the GPG key handling unless we can handle some edge cases.

My primary concern is the risk of a compromised public kernel module repo where modules, signatures, and the signing key stored in the repository have been replaced.

We could try pinning the default signing key fingerprint in margarita shotgun.  That should let us throw appropriate alarms if we get an unexpected signing key.  We would have to allow the pinned fingerprint to be overridden for users hosting their own kernel module repo however.

I would feel much more comfortable implementing an automatic import if we were pinning fingerprints etc, I may be missing an obvious solution to this however, I am curious what you think.

**Comment by andrewkrug** [comment]
Should we create the equivalent of a flag to auto-install gpg if necessary?  Equiv to `yum update -y` where if new keys are found it just installs them.

I agree that mitm is a concern.  

> We could try pinning the default signing key fingerprint in margarita shotgun. That should let us throw appropriate alarms if we get an unexpected signing key. 

Key pinning is historically problematic for anything that you don't control 100% of the install base for.  Unless you are willing to just break everything out there if you ever need to rotate the pinned key.  ( See HPKP in CSP ) 

I could also see us provided a packed AMI or something + docker container with the key included.  I think this is reasonable as a way to make it zero touch.

**Comment by andrewkrug** [comment]
https://github.com/ThreatResponse/aws_ir/commit/3920e1e68cc4daf444d8afe25c506e1ca75ae739
