### ISSUE TITLE
2017-08-17T08:35:21 - aws_ir.libs.volatile - CRITICAL - GPG key not in trust chain attempting interacti None

### ISSUE THREAD

**Issue by SeCCT12** [ThreatResponse/aws_ir#67]
Hi guys ,
I'm trying to run "./aws_ir --verbose --bucket-name XXXX --examiner-cidr-range  XXXX comromise --target XXXX --user ec2-user --ssh-key  XXXX " , but after attempting margerita shot gun part I'm receiving the error "2017-08-17T08:35:21 - aws_ir.libs.volatile - CRITICAL - GPG key not in trust chain attempting interactive installation." . I did add the aws certificate to the trust chain but it didn't help.
Can you please assist ?

**Comment by ac-milan** [comment]
I'm also facing the same issue, and the worst part is that after it fails it shuts down the instance!

2017-08-17T12:46:13 - margaritashotgun.repository - DEBUG - gpg verification enabled, initializing gpg
2017-08-17T12:46:13 - aws_ir.libs.volatile - CRITICAL - GPG key not in trust chain attempting interactive installation.
None
2017-08-17T12:46:13 - aws_ir.plans.host - ERROR - Memory acquisition failure with exception 'NoneType' object has no attribute '__getitem__'.
2017-08-17T12:46:13 - aws_ir.plans.host - INFO - Executing step stop_host.

**the GPG key was properly installed prior to running aws_ir:**

(aws_ir_env)[ec2-user@ip-10-200-0-129 aws_ir_env]$ curl -s https://threatresponse-lime-modules.s3.amazonaws.com/REPO_SIGNING_KEY.asc | gpg --import
gpg: directory `/home/ec2-user/.gnupg' created
gpg: new configuration file `/home/ec2-user/.gnupg/gpg.conf' created
gpg: WARNING: options in `/home/ec2-user/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/home/ec2-user/.gnupg/secring.gpg' created
gpg: keyring `/home/ec2-user/.gnupg/pubring.gpg' created
gpg: /home/ec2-user/.gnupg/trustdb.gpg: trustdb created
gpg: key 67172B17: public key "Lime Signing Key (Threat Response Official Lime Signing Key) <security@threatresponse.cloud>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)


please advise

Thanks.

**Comment by andrewkrug** [comment]
Hello to both of you @ac-milan and @SeCCT12 .  Thanks for filing this issue!  Can you tell me a little bit more about what system you're running AWS_IR on and also what type of system you're trying to acquire the important bits to know are:

* OS Variant (RHEL UBUNTU etc.)
* What's the VPC setup is this a public or private IP you're acquiring.

If you could also paste your command args that would be great.

**Comment by andrewkrug** [comment]
Also @ac-milan if you want to avoid instance-stop on failure use the `--plugins  examineracl_host,gather_host,isolate_host,snapshotdisks_host,stop_host,tag_host,get_memory`

This allows you to specify the order in which you want to run the plugin.steps.  You can simply leave out get_memory.  *Note that they will run in whatever order you specify in the list*

**Comment by SeCCT12** [comment]
Hi andrewkrug,
Instance is running in AWS environment  and below is the output of the installed image:
"4.9.32-15.41.amzn1.x86_64 #1 SMP Thu Jun 22 06:20:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux" .

The query includes the instance private and public IP addresses.
 
Please let me know if you need further information.
thanks in advance
Ofer

**Comment by SeCCT12** [comment]
Hi Andrewkrug,
Following my last comment, I've also verified that all requirements are already satisfied and I would appreciate if you can guide me with my next steps.
Thanks in advance
Ofer

**Comment by SeCCT12** [comment]
@andrewkrug  sure. Let me know what what to do next. the problem remained the same .

**Comment by SeCCT12** [comment]
Hi Andrew, Can you please share your email in private, so we could collaborate more effectively ? 
Thanks in advance
Ofer

**Comment by jparr** [comment]
Signing keys were renewed and are long lived now so hopefully we won't run into this again!
