### ISSUE TITLE
AttributeError: 'Plugin' object has no attribute '_Plugin__generate_inline_policy'

### ISSUE THREAD

**Issue by ryanp77** [ThreatResponse/aws_ir#83]
Receiving following error when attempt to run key-compromise.  Any help greatly appreciated.
```
> (aws_ir_env) [ec2-user@ip-10-0-1-145 venv]$ aws_ir key-compromise --access-key-id ***ACCESSKEY***
> 2018-07-06T20:39:32 - aws_ir.cli - INFO - Initialization successful proceeding to incident plan.
> 2018-07-06T20:39:32 - aws_ir.plans.key - INFO - Attempting key disable.
> Traceback (most recent call last):
>   File "/home/ec2-user/venv/aws_ir_env/bin/aws_ir", line 10, in <module>
>     c.run()
>   File "/home/ec2-user/venv/aws_ir_env/lib/python3.7/site-packages/aws_ir/cli.py", line 245, in run
>     kc.mitigate()
>   File "/home/ec2-user/venv/aws_ir_env/lib/python3.7/site-packages/aws_ir/plans/key.py", line 62, in mitigate
>     dry_run=False
>   File "/home/ec2-user/venv/aws_ir_env/lib/python3.7/site-packages/aws_ir_plugins/revokests_key.py", line 25, in __init__
>     self.setup()
>   File "/home/ec2-user/venv/aws_ir_env/lib/python3.7/site-packages/aws_ir_plugins/revokests_key.py", line 33, in setup
>     policy_document = self.__generate_inline_policy()
> AttributeError: 'Plugin' object has no attribute '_Plugin__generate_inline_policy'
```

**Comment by chilithomas** [comment]
Hey you just should me this one, haha good catch btw... and hopefully these genius developers answer this one.

**Comment by ryanp77** [comment]
@jparr 
Have attempted multiple installs.  Currently it is using 0.3.1.  I am utilizing the "Local Execution" method outlined in the documents.  Have attempted using multiple virtualenv with python 3.7 and now currently using 3.5.5.  Same error with 3.7 and 3.5.5.  

And you assumed correctly, it is a real "test" access key ID that I created for this purpose only.

Please let me know if any other info can assist.

**Comment by jparr** [comment]
I really need to improve the logging and debug output for this tool. 

Assuming `pip install -r requirements` went ok? Can you give me the output of `pip list -l`

**Comment by chilithomas** [comment]
Hey guys I cloned https://github.com/ThreatResponse/aws_ir_plugins to ~/aws_ir/aws_ir_plugins/ then copied revokests_key.py to ~/aws_ir/venv/lib/python3.5/site-packages/aws_ir_plugins/revokests_key.py.
Looks like the key disable worked when I check the key in the IAM console, but I'd like to test again.

**Comment by chilithomas** [comment]
Sweet .. and yes I think the doc like http://aws-ir.readthedocs.io/en/latest/quickstart.html should say something like source aws_ir_env/bin/activate but now I'm just nit picking ;) .. Thanks for the quick response!

**Comment by jparr** [comment]
@chilithomas - Did you also try to use the 'Local Execution' instructions? Did either of you try to pip install the package fro pypi?

**Comment by ryanp77** [comment]
Did try the pip install, had same issue no matter where the install came from!  I think that @chilithomas was able to get it working for us.  Greatly appreciate you fast response.  Looking forward to stretching the legs of this toolkit.

**Comment by jparr** [comment]
Thanks for the heads up folks! I'll try to cut a new version and walk through all the docs this weekend to make sure everything works.

**Comment by jparr** [comment]
I replicated this issue by doing a fresh install. It was due to an old version of aws_ir_plugins on pypi.
I published a new version of the plugins and started with a fresh docker container. I was able to run revokests_key without issue.
